package br.edu.garanhuns.sysreservajsf.entity;
// Generated 14/11/2016 19:17:57 by Hibernate Tools 4.3.1

import java.util.LinkedHashSet;
import java.util.Set;




/**
 * Equipamento generated by hbm2java
 */
public class Equipamento {


     private Integer id;
     private String nome;
     private String marca;
     private String tipo;
     private String utilidade;
     private Set<Aula> aulas = new LinkedHashSet<Aula>();

    public Integer getId() {
        return id;
    }

    private void setId(Integer id) {
        this.id = id;
    }

    public String getNome() {
        return nome;
    }

    public void setNome(String nome) {
        this.nome = nome;
    }

    public String getMarca() {
        return marca;
    }

    public void setMarca(String marca) {
        this.marca = marca;
    }

    public String getTipo() {
        return tipo;
    }

    public void setTipo(String tipo) {
        this.tipo = tipo;
    }

    public String getUtilidade() {
        return utilidade;
    }

    public void setUtilidade(String utilidade) {
        this.utilidade = utilidade;
    }

    public Set<Aula> getAulas() {
        return aulas;
    }

    public void setAulas(Set<Aula> aulas) {
        this.aulas = aulas;
    }
     
     

    
}


